// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqnwyYgSq5_b80FVx8HWYZVLCR00ofay0',
    appId: '1:950056052674:web:7dccde5c663b7e0463585b',
    messagingSenderId: '950056052674',
    projectId: 'sikopi-91281',
    authDomain: 'sikopi-91281.firebaseapp.com',
    storageBucket: 'sikopi-91281.appspot.com',
    measurementId: 'G-ZV3GQ8DR8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCY5fTHeNrrsClW_NkA0rifYDbmXHe_vU',
    appId: '1:950056052674:android:0a165cdc3f1fff0c63585b',
    messagingSenderId: '950056052674',
    projectId: 'sikopi-91281',
    storageBucket: 'sikopi-91281.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeNhvk2xPghCqDAWzbr0FGaz1HinxLMfg',
    appId: '1:950056052674:ios:743500c616cc0aea63585b',
    messagingSenderId: '950056052674',
    projectId: 'sikopi-91281',
    storageBucket: 'sikopi-91281.appspot.com',
    iosClientId: '950056052674-ii8m6l1fivob115utpfqavmi232ntg3e.apps.googleusercontent.com',
    iosBundleId: 'com.example.sikopi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeNhvk2xPghCqDAWzbr0FGaz1HinxLMfg',
    appId: '1:950056052674:ios:743500c616cc0aea63585b',
    messagingSenderId: '950056052674',
    projectId: 'sikopi-91281',
    storageBucket: 'sikopi-91281.appspot.com',
    iosClientId: '950056052674-ii8m6l1fivob115utpfqavmi232ntg3e.apps.googleusercontent.com',
    iosBundleId: 'com.example.sikopi',
  );
}
